version: "3.8"

services:
  covid-user-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./userdatabase/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -p 6001
#    ports:
#      - "5432:5432"

  covid-location-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./userdatabase/init_location.sql:/docker-entrypoint-initdb.d/init_location.sql
    command: -p 6002

  user-service:
    image: userservice:0.0.1
    ports:
      - "5001:5001"
    depends_on:
      - covid-user-db

  location-service:
    image: location_service:0.0.1
    ports:
      - "3001:3001"
    depends_on:
      - covid-location-db
