version: "3.8"

services:
  pgadmin:
    depends_on:
      - covid-user-db
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  covid-user-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./userdatabase/init.sql:/docker-entrypoint-initdb.d/init.sql
#    command: -p 6001 # Uncomment if you want to launch the multi-services configuration
    ports: # Uncomment if you want individual service test development
      - "5432:5432"

  keycloak:
    depends_on:
      - covid-user-db
    container_name: local_keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json

      DB_VENDOR: POSTGRES
      DB_ADDR: covid-user-db
      DB_DATABASE: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "28080:8080"
    volumes:
      - ./config/keycloak/realm-export.json:/tmp/realm-export.json

  user-service:
    image: userservice:0.0.1
    ports:
      - "5001:5001"
    depends_on:
      - covid-user-db