variables:
  REPOSITORY_URL: 961822111490.dkr.ecr.us-east-1.amazonaws.com
  APP_NAME: covid-alert-services
  IMAGE_TAG: notificationservice
  ARTIFACT_NAME: notificationservice-0.0.1.jar

services:
  - docker:dind

stages:
  - build-jar
  - build-image
#  - deploy-image

before_script:
  - docker --version
  - apk add --no-cache curl jq python3 py3-pip
  - pip install awscli
  - aws --version
  - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
  - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
  - aws configure set region ${AWS_DEFAULT_REGION}
  - aws configure list

build-microservice-jar:
  image: openjdk:16-jdk-alpine
  stage: build-jar

  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - echo $ARTIFACT_NAME
  script:
    - ls -l notificationservice/
    - ./gradlew notificationservice:bootJar
    - ls -l notificationservice/build/libs/
  artifacts:
    paths:
      - notificationservice/build/libs/*.jar
  only:
    - master

build-docker-image:
  stage: build-image

  script:
    - echo "Building image..."
    - ls -l notificationservice/build/libs/
    - docker build -t $REPOSITORY_URL/$APP_NAME:$IMAGE_TAG ./notificationservice
    - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URL
    - echo "Pushing image..."
    - docker push $REPOSITORY_URL/$APP_NAME:$IMAGE_TAG
  only:
    - master
