server:
  port: 8888

spring:
 cloud:
  config:
   server:
    git:
     uri: https://github.com/AyoubMoujane/covid-alert-backend-config.git
     username: github-username
     password: generate-personal-access-token
     default-label: "main"