server:
  port: 5001
eureka:
  client:
    serviceUrl:
      # Docker
      defaultZone: http://discovery-service:8761/eureka/
      # Manual gradle version
      # defaultZone: http://localhost:8761/eureka/

    # Database location configurations

spring.datasource:
  # Uncomment when launching using docker-compose
  url: jdbc:postgresql://covid-user-db:5432/
  # Uncomment using bootRun through gradle
  #  url: jdbc:postgresql://localhost:5432/
  username: postgres
  password: postgres
spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: none
  hibernate.show-sql: true

app.version: 1.0.0
logging.level.org.springframework.security: DEBUG
spring.application.name: user-service
eureka.instance.instance-id: ${spring.application.name}:${random.uuid}

# Docker version
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://keycloak:8080/auth/realms/microservices-realm
# Manual gradle version
#security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:28080/auth/realms/microservices-realm