server:
  port: 5001
eureka:
  client:
    serviceUrl:
      # Docker
      defaultZone: http://discovery-service:8761/eureka/
      # Manual gradle version
      # defaultZone: http://localhost:8761/eureka/