image: docker:20
#image: ruby:2.6

variables:
  DOCKER_REGISTRY: 961822111490.dkr.ecr.us-east-1.amazonaws.com/covid-alert-services
  AWS_DEFAULT_REGION: us-east-1
  APP_NAME: covid-alert-services

services:
  - docker:dind

before_script:
  - docker --version
  - apk add --no-cache curl python3 py3-pip
  - pip install awscliv2
  - awsv2 --version
  - awsv2 configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - awsv2 configure set aws_secret_access_key_id $AWS_SECRET_ACCESS_KEY
  - awsv2 configure set region $AWS_DEFAULT_REGION

stages:
  - build

build-docker-image:
  stage: build
  script:
    - docker build -t "$DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IDD" .
    - awsv2 ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IDD
  only:
    - pipelineCiCd-Pierre