variables:
  DOCKER_REGISTRY: 961822111490.dkr.ecr.us-east-1.amazonaws.com
  APP_NAME: covid-alert-services

services:
  - docker:dind

stages:
#  - build-jar
  - build-image

#build-microservice-jar:
#  stage: build-jar
#  image: gradle:jdk16
#  before_script:
#    - export GRADLE_USER_HOME=`pwd`/.gradle
#  script:
#    - ./gradlew assemble


build-docker-image:
  stage: build-image

  before_script:
    - docker --version
    - apk add --no-cache curl python3 py3-pip
    - pip install awscli
    - aws --version
    - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
    - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
    - aws configure set region ${AWS_DEFAULT_REGION}
#    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
#    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
#    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    - aws configure list

  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID ./userservice
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IDD
  only:
    - pipelineCiCd-Pierre