image: docker:20
#image: ruby:2.6

variables:
  DOCKER_REGISTRY: 961822111490.dkr.ecr.us-east-1.amazonaws.com
  APP_NAME: covid-alert-services
  DOCKER_HOST: tcp://docker:2375

stages:
  - build

build-docker-image:
  stage: build
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl python3 py3-pip
    - pip install awscli
    - aws --version
    - aws configure set aws_access_key_id AKIA574IQW4BPBAMRGLB
    - aws configure set aws_secret_access_key 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
    - aws configure set region us-east-1
#    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
#    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
#    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID ./userservice
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IDD
  only:
    - pipelineCiCd-Pierre