image: docker:20
#image: ruby:2.6

variables:
  DOCKER_REGISTRY: 961822111490.dkr.ecr.us-east-1.amazonaws.com
  AWS_DEFAULT_REGION: us-east-1
  APP_NAME: covid-alert-services
  DOCKER_HOST: tcp://docker:2375


stages:
  - build

build-docker-image:
  stage: build
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl python3 py3-pip
    - pip install awscli
    - aws --version
  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID ./userservice
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IDD
  only:
    - pipelineCiCd-Pierre