variables:
  DOCKER_REGISTRY: 961822111490.dkr.ecr.us-east-1.amazonaws.com
  APP_NAME: covid-alert-services
  MICROSERVICE_NAME: userservice

services:
  - docker:dind

stages:
#  - build-jar
  - build-image



build-docker-image:
  stage: build-image

  before_script:
    - docker --version
    - apk add --no-cache curl python3 py3-pip
    - pip install awscli
    - aws --version
    - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
    - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
    - aws configure set region ${AWS_DEFAULT_REGION}
    - aws configure list

  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$MICROSERVICE_NAME ./userservice
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$APP_NAME:$MICROSERVICE_NAME
  only:
    - pipelineCiCd-Pierre